# Generated by Django 4.1 on 2022-10-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('run', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=150)),
                ('comentario', models.CharField(max_length=150, null=True)),
                ('fono', models.IntegerField()),
            ],
        ),
    ]
