# Generated by Django 4.1 on 2022-11-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('MarcaModel', 'Marca')
    ]
